# ==============================================================================
# Config.yml
# ------------------------------------------------------------------------------
#
# This is the main configuration file for the website. The 'theme' value should
# match the name of the folder in /themes that contains your theme files; if
# you've copied the default theme and given it a different name make sure to
# update the value here too.

baseURL: ""

title: "Quire Starter"
languageCode: "en-us"
theme: "quire-starter-theme"
publishDir: site

footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"
googleAnalytics: ""

pluralizeListTitles: true
disableKinds:
  - "home"
  - "section"
  - "taxonomy"
  - "taxonomyTerm"

blackfriday:
  fractions: false
  hrefTargetBlank: true

# These values can be accessed in templates via .Site.Params
params:
  searchEnabled: true
  licenseIcons: true
  citationPageLocationDivider: ", "
  figureLabels: false
  figureLabelsTextBefore: "Figure "
  figureLabelsTextAfter: ". "
  videoFigureFallbackText: true
  videoFigureFallbackTextBefore: "Watch the video at "
  videoFigureFallbackTextAfter: ". "
  websiteFigureFallbackText: true
  websiteFigureFallbackTextBefore: "Visit the site at "
  websiteFigureFallbackTextAfter: ". "
  displayBiblioShort: false
  imageDir: "img"
  tocType: short
  menuType: short
  objectLinkText: "View in Collection"
  frontmatterPageStart: 0
  bodyPageStart: 100
  backmatterPageStart: 1000
# ==============================================================================
#  web.yml
# ------------------------------------------------------------------------------
#
# Build-specific values. Hugo supports multiple config files with the
# following syntax:
#
# hugo --config=base.toml,child1.toml,child2.toml
#
# If you are using the Quire commands, this will happen automatically.

baseURL: ""
relativeURLs: true
# ==============================================================================
# netlify.yml
# ------------------------------------------------------------------------------
#
# Deployment config for https://www.netlify.com/
# The baseURL should be updated to your Netlify subdomain
#
# You will also need to add a `netlify.toml` file with the following:
# [build]
#   publish = "site"
#   command = "hugo --config=config.yml,config/web.yml,config/environments/netlify.yml"
#   HUGO_VERSION = "0.31"


# Use these settings for Netlify
#
baseURL: "http://quire-demo.netlify.com"
relativeURLs: true
