# ==============================================================================
#  web.yml
# ------------------------------------------------------------------------------
#
# Build-specific values. Hugo supports multiple config files with the
# following syntax:
#
# hugo --config=base.toml,child1.toml,child2.toml
#
# If you are using the Quire commands, this will happen automatically.

baseURL: "https://mystifying-bhaskara-e62fdc.netlify.com"
relativeURLs: true
